src/Entity/Donation.php
<?php

namespace App\Entity;

use App\Repository\DonationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: DonationRepository::class)]
class Donation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    #[Assert\NotBlank(message: "nombre passe ne peux pas être vide! ")]
    #[Assert\Positive(message: "nombre passe doit etre positive! ")]
    private ?float $amount = null;
    

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "message evennement ne peux pas être vide! ")]
    private ?string $message = null;

    #[ORM\ManyToOne]
    private ?Event $event = null;

    #[ORM\ManyToOne]
    private ?User $Utilisateur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(?Event $event): static
    {
        $this->event = $event;

        return $this;
    }

    public function getUtilisateur(): ?User
    {
        return $this->Utilisateur;
    }

    public function setUtilisateur(?User $Utilisateur): static
    {
        $this->Utilisateur = $Utilisateur;

        return $this;
    }
}

src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "titre evennement ne peux pas être vide! ")]
    #[Assert\Length(
        min: 3,
        max: 10,
        minMessage: "The name must be at least {{ limit }} characters long",
        maxMessage: "The name cannot be longer than {{ limit }} characters"
    )]
    private ?string $nom_event = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\GreaterThan("today", message: "date inferieur a aujourd'hui.")]
    private ?\DateTimeInterface $date_event = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "adresse evennement ne peux pas être vide! ")]
    #[Assert\Length(
        min: 3,
        max: 20,
        minMessage: "The name must be at least {{ limit }} characters long",
        maxMessage: "The name cannot be longer than {{ limit }} characters"
    )]
    private ?string $adress_event = null;

    
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "description evennement ne peux pas être vide! ")]
    #[Assert\Length(
        min: 7,
        max: 20,
        minMessage: "The name must be at least {{ limit }} characters long",
        maxMessage: "The name cannot be longer than {{ limit }} characters"
    )]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomEvent(): ?string
    {
        return $this->nom_event;
    }

    public function setNomEvent(string $nom_event): static
    {
        $this->nom_event = $nom_event;

        return $this;
    }

    public function getDateEvent(): ?\DateTimeInterface
    {
        return $this->date_event;
    }

    public function setDateEvent(\DateTimeInterface $date_event): static
    {
        $this->date_event = $date_event;

        return $this;
    }

    public function getAdressEvent(): ?string
    {
        return $this->adress_event;
    }

    public function setAdressEvent(string $adress_event): static
    {
        $this->adress_event = $adress_event;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }
    public function __toString()
    {
        return $this->nom_event;
    }
}

src/Form/DonationType.php
<?php

namespace App\Form;

use App\Entity\Donation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DonationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('amount')
            ->add('message')
            
            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Donation::class,
        ]);
    }
}

src/Controller/DonationController.php
<?php

namespace App\Controller;

use App\Entity\Donation;
use App\Form\DonationType;
use App\Repository\DonationRepository;
use App\Repository\EventRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Dompdf\Dompdf;
use Dompdf\Options;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use App\Entity\Event;
use Symfony\Component\Security\Core\Security;
use Knp\Component\Pager\PaginatorInterface;

#[Route('/donation')]
class DonationController extends AbstractController
{
    #[Route('/', name: 'app_donation_index', methods: ['GET'])]
    public function index(DonationRepository $donationRepository,PaginatorInterface $paginator,Request $request): Response
    {

        $query = $donationRepository->createQueryBuilder('p')
            ->orderBy('p.id', 'ASC')
            ->getQuery();

        $pagination = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            5
        );

        return $this->render('donation/index.html.twig', [

            'donations' => $pagination,

        ]);
        /*
        return $this->render('donation/index.html.twig', [
            'donations' => $donationRepository->findAll(),
        ]);
        */
    }

    #[Route('/new/{id}', name: 'app_donation_new', methods: ['GET', 'POST'])]
    public function new(EventRepository $eventRepository,Request $request, EntityManagerInterface $entityManager,MailerInterface $mailer,$id,Security $security): Response
    {
        
      
        $event = $eventRepository->find($id);
        $user = $security->getUser();

        if (!$event) {
            throw $this->createNotFoundException('The event does not exist');
        }
        if (!$user) {
            throw $this->createNotFoundException('You must be logged in to make a donation');
        }
        $donation = new Donation();
        $donation->setEvent($event);
        $donation->setUtilisateur($user); 
        $form = $this->createForm(DonationType::class, $donation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($donation);
            $entityManager->flush();
            $msg='your donation for event: '.$event->getNomEvent().' is confirmed';
            $email = (new Email())
        ->from('gadourkaddachi000@gmail.com')
        ->to($user->getUserIdentifier())
        ->subject('DONATION')
        ->text($msg);

    // Send the email
    $mailer->send($email);

            return $this->redirectToRoute('app_event_index_front', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('donation/new.html.twig', [
            'donation' => $donation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_donation_show', methods: ['GET'])]
    public function show(Donation $donation): Response
    {
        return $this->render('donation/show.html.twig', [
            'donation' => $donation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_donation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Donation $donation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DonationType::class, $donation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_donation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('donation/edit.html.twig', [
            'donation' => $donation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_donation_delete', methods: ['POST'])]
    public function delete(Request $request, Donation $donation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$donation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($donation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_donation_index', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('/donation/pdf', name: 'app_donation_pdf', methods: ['GET'])]
public function pdf(DonationRepository $donationRepository): Response
{
    $donations = $donationRepository->findAll();

    // Generate HTML content for the list of donations
    $pdfOptions = new Options();
        $pdfOptions->set('defaultFont', 'Arial');

        // Instantiate Dompdf with our options
        $dompdf = new Dompdf($pdfOptions);



        // Retrieve the HTML generated in our twig file
        $html = $this->renderView('donation/pdf.html.twig', [
            'donations' => $donations,
        ]);

        // Load HTML to Dompdf
        $dompdf->loadHtml($html);

        // (Optional) Setup the paper size and orientation 'portrait' or 'portrait'
        $dompdf->setPaper('A4', 'portrait');

        // Render the HTML as PDF
        $dompdf->render();

        $output = $dompdf->output();

        $publicDirectory = $this->getParameter('donation_pdf_directory');

        $pdfFilepath =  $publicDirectory . '/' . uniqid() . '.pdf';
        if (!file_exists($pdfFilepath)) {
            file_put_contents($pdfFilepath, $output);
            return new Response("The PDF file has been succesfully generated !");
        } else {
            return new Response("The PDF file already exist");
        }



        // Output the generated PDF to Browser (force download)

    }
    #[Route('/donation/recu', name: 'app_donation_mail', methods: ['GET'])]
    public function sendEmail(MailerInterface $mailer)
{
    // Create a new Email message
    $email = (new Email())
        ->from('mailjavam@gmail.com')
        ->to('recipient@example.com')
        ->subject('DONATION')
        ->text('your donation is confirmed.');

    // Send the email
    $mailer->send($email);

    // Optionally, handle any exceptions
}

}

templates/donation/_delete_form.html.twig
<form method="post" action="{{ path('app_donation_delete', {'id': donation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ donation.id) }}">
    <button class = "btn btn-danger">Delete</button>
</form>

templates/donation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/donation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Donation{% endblock %}

{% block body %}
    <h1>Edit Donation</h1>

    {{ include('donation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_donation_index') }}">back to list</a>

    {{ include('donation/_delete_form.html.twig') }}
{% endblock %}

templates/donation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Donation index{% endblock %}

{% block body %}
    <h1>Donation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Amount</th>
                <th>Message</th>
                <th>event</th>
                <th>Donor</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for donation in donations %}
            <tr>
                <td>{{ donation.id }}</td>
                <td>{{ donation.amount }}</td>
                <td>{{ donation.message }}</td>
                <td>{{ donation.event.nomEvent }}</td>
                <td>{{ donation.utilisateur.email }}</td>
                <td>
                    <a href="{{ path('app_donation_show', {'id': donation.id}) }}" class = "btn btn-info">show</a>
                    
                    
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div style="text-align: center; margin-top: 20px;">
    <div class="pagination" style="display: inline-block;">
        {{ knp_pagination_render(donations) }}
    </div>
</div>
<a href="{{ path('app_donation_pdf') }}" class = "btn btn-primary">PDF</a>
    
{% endblock %}

templates/donation/new.html.twig
{% extends 'frontEvent.html.twig' %}

{% block title %}New Donation{% endblock %}

{% block body %}
    <h1>Create new Donation</h1>

    {{ include('donation/_form.html.twig') }}

    <a href="{{ path('app_donation_index') }}" class = "btn btn-primary">back to list</a>
{% endblock %}

templates/donation/newfront.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Donation{% endblock %}

{% block body %}
    <h1>Create new Donation</h1>

    {{ include('donation/_form.html.twig') }}

    <a href="{{ path('app_donation_index') }}" class = "btn btn-primary">back to list</a>
{% endblock %}

templates/donation/pdf.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List of Donations</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>List of Donations</h1>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Amount</th>
                
                <th>Message</th>
                <th>donor</th>
                
                <th>event</th>
            </tr>
        </thead>
        <tbody>
            {% for donation in donations %}
                <tr>
                    <td>{{ donation.id }}</td>
                    <td>{{ donation.amount }}</td>
                    <td>{{ donation.message }}</td>
                    <td>{{ donation.utilisateur.email }}</td>
                    <td>{{ donation.event.nomEvent }}</td>
                    
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">No donations found</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

templates/donation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Donation{% endblock %}

{% block body %}
    <h1>Donation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ donation.id }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ donation.amount }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ donation.message }}</td>
            </tr>
            <tr>
                <th>Donor</th>
                <td>{{ donation.utilisateur.email }}</td>
            </tr>
             <tr>
                <th>Event</th>
                <td>{{ donation.event.nomEvent }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_donation_index') }}" class = "btn btn-primary">back to list</a>

    

    {{ include('donation/_delete_form.html.twig') }}
{% endblock %}